services:
  - type: web
    name: asadete-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install && npx prisma generate
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: NODE_ENV
        value: production
    autoDeploy: true
